FROM logstash:latest
MAINTAINER Salzburg Research <nimble-srfg@salzburgresearch.at>

ADD config/logstash.conf /etc/logstash/conf.d/logstash.conf

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json 
